//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedLamp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkedLamp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Global_Error {
            get {
                return ResourceManager.GetString("Global_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next.
        /// </summary>
        public static string Global_Next {
            get {
                return ResourceManager.GetString("Global_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string Global_Ok {
            get {
                return ResourceManager.GetString("Global_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Global_Password {
            get {
                return ResourceManager.GetString("Global_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change password.
        /// </summary>
        public static string Home_AccountHamburgerMenu_ChangePassword {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm new password:.
        /// </summary>
        public static string Home_AccountHamburgerMenu_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current password:.
        /// </summary>
        public static string Home_AccountHamburgerMenu_CurrentPassword {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current password is incorrect..
        /// </summary>
        public static string Home_AccountHamburgerMenu_CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete account.
        /// </summary>
        public static string Home_AccountHamburgerMenu_DeleteAccount {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Home_AccountHamburgerMenu_DeleteAccount_ConfirmDeleteButton {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_DeleteAccount_ConfirmDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This will delete your account and all owned groups. Continue?.
        /// </summary>
        public static string Home_AccountHamburgerMenu_DeleteAccount_ConfirmMessage {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_DeleteAccount_ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logout.
        /// </summary>
        public static string Home_AccountHamburgerMenu_Logout {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New password:.
        /// </summary>
        public static string Home_AccountHamburgerMenu_NewPassword {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New password is too short..
        /// </summary>
        public static string Home_AccountHamburgerMenu_NewPasswordTooShort {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_NewPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords do not match..
        /// </summary>
        public static string Home_AccountHamburgerMenu_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password updated..
        /// </summary>
        public static string Home_AccountHamburgerMenu_PasswordUpdated {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account.
        /// </summary>
        public static string Home_AccountHamburgerMenu_Title {
            get {
                return ResourceManager.GetString("Home_AccountHamburgerMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure LinkedLamp.
        /// </summary>
        public static string Home_ConfigureLinkedLampButton {
            get {
                return ResourceManager.GetString("Home_ConfigureLinkedLampButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect to account.
        /// </summary>
        public static string Home_ConnectToAccountButton {
            get {
                return ResourceManager.GetString("Home_ConnectToAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create account.
        /// </summary>
        public static string Home_CreateAccountButton {
            get {
                return ResourceManager.GetString("Home_CreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I forgot my password.
        /// </summary>
        public static string Home_ForgotPasswordButton {
            get {
                return ResourceManager.GetString("Home_ForgotPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage groups.
        /// </summary>
        public static string Home_ManageGroupsButton {
            get {
                return ResourceManager.GetString("Home_ManageGroupsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string Home_PageTitle {
            get {
                return ResourceManager.GetString("Home_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection failure..
        /// </summary>
        public static string Home_PasswordRecovery_ConnectionFailure {
            get {
                return ResourceManager.GetString("Home_PasswordRecovery_ConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email sending failed (SMTP not configured or error)..
        /// </summary>
        public static string Home_PasswordRecovery_EmailSendFailed {
            get {
                return ResourceManager.GetString("Home_PasswordRecovery_EmailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your username:.
        /// </summary>
        public static string Home_PasswordRecovery_EnterUsername {
            get {
                return ResourceManager.GetString("Home_PasswordRecovery_EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No email is associated with this account..
        /// </summary>
        public static string Home_PasswordRecovery_NoEmail {
            get {
                return ResourceManager.GetString("Home_PasswordRecovery_NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new password has been sent to the email associated with this account..
        /// </summary>
        public static string Home_PasswordRecovery_Sent {
            get {
                return ResourceManager.GetString("Home_PasswordRecovery_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password recovery.
        /// </summary>
        public static string Home_PasswordRecovery_Title {
            get {
                return ResourceManager.GetString("Home_PasswordRecovery_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User not found..
        /// </summary>
        public static string Home_PasswordRecovery_UserNotFound {
            get {
                return ResourceManager.GetString("Home_PasswordRecovery_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Login_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Login_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username and password are required..
        /// </summary>
        public static string Login_RequiredFieldsError {
            get {
                return ResourceManager.GetString("Login_RequiredFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect to account.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string Login_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("Login_UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string ManageGroup_AddUser_Add {
            get {
                return ResourceManager.GetString("ManageGroup_AddUser_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add user.
        /// </summary>
        public static string ManageGroup_AddUser_Title {
            get {
                return ResourceManager.GetString("ManageGroup_AddUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string ManageGroup_AddUser_Username {
            get {
                return ResourceManager.GetString("ManageGroup_AddUser_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add user.
        /// </summary>
        public static string ManageGroup_AddUserButton {
            get {
                return ResourceManager.GetString("ManageGroup_AddUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string ManageGroup_DeleteButton {
            get {
                return ResourceManager.GetString("ManageGroup_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete this group?.
        /// </summary>
        public static string ManageGroup_DeleteGroup_ConfirmMessage {
            get {
                return ResourceManager.GetString("ManageGroup_DeleteGroup_ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string ManageGroup_DeleteGroup_Delete {
            get {
                return ResourceManager.GetString("ManageGroup_DeleteGroup_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete group.
        /// </summary>
        public static string ManageGroup_DeleteGroup_Title {
            get {
                return ResourceManager.GetString("ManageGroup_DeleteGroup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave.
        /// </summary>
        public static string ManageGroup_LeaveButton {
            get {
                return ResourceManager.GetString("ManageGroup_LeaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to leave this group?.
        /// </summary>
        public static string ManageGroup_LeaveGroup_ConfirmMessage {
            get {
                return ResourceManager.GetString("ManageGroup_LeaveGroup_ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave.
        /// </summary>
        public static string ManageGroup_LeaveGroup_Leave {
            get {
                return ResourceManager.GetString("ManageGroup_LeaveGroup_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leave group.
        /// </summary>
        public static string ManageGroup_LeaveGroup_Title {
            get {
                return ResourceManager.GetString("ManageGroup_LeaveGroup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        public static string ManageGroup_Loading {
            get {
                return ResourceManager.GetString("ManageGroup_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manage group.
        /// </summary>
        public static string ManageGroup_PageTitle {
            get {
                return ResourceManager.GetString("ManageGroup_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove {0} from this group?.
        /// </summary>
        public static string ManageGroup_RemoveUser_ConfirmMessageFormat {
            get {
                return ResourceManager.GetString("ManageGroup_RemoveUser_ConfirmMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        public static string ManageGroup_RemoveUser_Remove {
            get {
                return ResourceManager.GetString("ManageGroup_RemoveUser_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove user.
        /// </summary>
        public static string ManageGroup_RemoveUser_Title {
            get {
                return ResourceManager.GetString("ManageGroup_RemoveUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove.
        /// </summary>
        public static string ManageGroup_RemoveUserButton {
            get {
                return ResourceManager.GetString("ManageGroup_RemoveUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename.
        /// </summary>
        public static string ManageGroup_RenameButton {
            get {
                return ResourceManager.GetString("ManageGroup_RenameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New name.
        /// </summary>
        public static string ManageGroup_RenameGroup_NewName {
            get {
                return ResourceManager.GetString("ManageGroup_RenameGroup_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename.
        /// </summary>
        public static string ManageGroup_RenameGroup_Rename {
            get {
                return ResourceManager.GetString("ManageGroup_RenameGroup_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rename group.
        /// </summary>
        public static string ManageGroup_RenameGroup_Title {
            get {
                return ResourceManager.GetString("ManageGroup_RenameGroup_Title", resourceCulture);
            }
        }
    }
}
